<?php

namespace App\Twig\Extension;

use Symfony\Bridge\Twig\Extension\AssetExtension as BaseExtension;
use Symfony\Component\Asset\Packages;


class AssetExtension extends BaseExtension
{
    private $usePrefix;

    public function __construct(Packages $packages)
    {
        parent::__construct($packages);
    }

    public function getAssetUrl($path, $packageName = null)
    {
        return parent::getAssetUrl($path, $packageName); // TODO: Change the autogenerated stub
    }

}